# Apps
brew cask install vscode
brew cask install firefox
brew cask install fantastical
brew cask install slack
brew cask install discord
brew cask install focus
brew cask install 1password
brew cask install google-chrome
brew cask install gimp
brew cask install postman
brew cask install obs
brew cask install rescuetime
brew cask install minecraft
brew cask install skim
brew cask install the-unarchiver
brew cask install the-archive-browser
brew cask install steam
brew cask install spotify
